# Site settings
name: Matthew Kipp
email: kippmr@gmail.com
#canonical_url: https://kippmr.com
keywords: "Software Development, C#, Java, JavaScript, ASP .NET, Angular, React, Agile Project Management"
skills: "Full Stack Software Developer <br>McMaster University"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/kippmr/
  - title: github
    url: https://github.com/kippmr
    
# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F



# Build settings
markdown: kramdown
permalink: pretty
